config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :body, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }


  def user_name
    user.present? ? user.name : super
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_comment, only: [:destroy]

  # POST /comments
  def create
    @new_comment = @event.comments.build(comment_params)
    @new_comment.user = current_user

    if @new_comment.save
      notify_subscribers(@event, @new_comment)
      redirect_to @event, notice: t('controllers.comments.created')
    else
      render 'events/show', alert: t('controllers.comments.error')
    end
  end

  def destroy
    message = {notice: t('controllers.comments.destroyed')}

    if current_user_can_edit?(@comment)
      @comment.destroy!
    else
      message = {alert: t('controllers.comments.error')}
    end

    redirect_to @event, message
  end

  private

  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_comment
    @comment = @event.comments.find(params[:id])
  end

  def comment_params
    params.require(:comment).permit(:body, :user_name)
    #params.fetch(:comment, {})
  end

  def notify_subscribers(event, comment)
    all_emails = (@event.subscriptions.map(&:user_email) + [@event.user.email] - [current_user&.email]).uniq.compact

    all_emails.each do |mail|
      EventMailer.comment(event, comment, mail).deliver_later
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.buffer-bottom
  p.text-justify = comment.body
  p
    span
      - if comment.user.present?
        => render partial: 'users/user', object: comment.user
      - else
        em
          strong
            => comment.user_name
    em
      => l comment.created_at, format: :short
    - if current_user_can_edit?(comment)
      => link_to event_comment_path(comment.event, comment),
            method: :delete, data: {confirm: t('.destroy_confirm')} do
        span.fas.fa-trash style="color: red"

app/views/comments/_form.html.slim
= form_for [@event, comment] do |f|
  = render partial: 'partials/form_errors', locals: {model: comment}
  .form-group
    = f.label :body
    = f.text_area :body, class: 'form-control'
  - unless user_signed_in?
    .form-group
      = f.label :user_name
      = f.text_field :user_name, class: 'form-control'
  .actions
    = f.submit 'Отправить', class: 'btn btn-primary'