config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  has_many :events
  has_many :comments
  has_many :subscriptions

  validates :name, presence: true, length: {maximum: 35}
  validates :email, presence: true, length: {maximum: 255}, uniqueness: true, 'valid_email_2/email': true, on: [
    :create, :update, :edit
  ]

  validates_presence_of :avatar, on: [:edit]

  before_validation :set_name, on: :create

  after_commit :link_subscriptions, on: :create

  mount_uploader :avatar, AvatarUploader

  private

  def link_subscriptions
    Subscription.where(user_id: nil, user_email: self.email)
      .update_all(user_id: self.id)
  end

  def send_devise_notification(notification, *args)
    devise_mailer.send(notification, self, *args).deliver_later
  end

  # Задаем юзеру случайное имя, если оно пустое
  def set_name
    self.name = "Товарисч №#{rand(7777)}" if self.name.blank?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]
  before_action :set_current_user, except: [:show]

  def show
    @user = User.find(params[:id])
  end


  def edit
  end

  def update
      if @user.update(user_params)
        redirect_to @user, notice: I18n.t('controllers.users.updated')
      else
        render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_current_user
    @user = current_user
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_params
    params.require(:user).permit(:name, :email, :avatar)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.slim
= form_for @user, html: { multipart: true } do |f|
  = render partial: 'partials/form_errors', locals: {model: @user}
  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :email
    = f.email_field :email, class: 'form-control'
  .form-group
    = f.label :avatar
    p = image_tag(@user.avatar.thumb.url) if @user.avatar?
    = f.file_field :avatar
  .actions
    = f.submit 'Сохранить', class: 'btn btn-primary'
    '
    = link_to 'вернуться', :back, class: 'btn btn-success'

app/views/users/_user.html.slim
span.user
  span.user-avatar
    => image_tag(user_avatar(user), class: 'img-icon')
  span.user-name
    - if request.path == user_path(user)
      = user.name
    - else
      = link_to user.name, user_path(user)

app/views/users/edit.html.slim
h1 Редактирование профиля
.row
  .col-md-6.buffer-top
    = render 'form'

    p.buffer-top
      = link_to 'Сменить пароль', edit_user_registration_path

app/views/users/show.html.slim
.text-center
  h1 = @user.name
  = image_tag user_avatar(@user)
  - if @user == current_user
    p.buffer-top = link_to "Редактировать профиль", edit_user_path(@user), class: 'btn btn-dark'
  .row
    .col-md-12
      - if @user.events.any?
        h3 Организовал:
        .row
          = render partial: 'events/event', collection: @user.events
      - else
        p.buffer-top Пользователь не замечен в организации мероприятий