config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/event.rb
class Event < ApplicationRecord

  belongs_to :user
  has_many :comments, dependent: :destroy
  has_many :subscriptions, dependent: :destroy
  has_many :subscribers, through: :subscriptions, source: :user, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :user, presence: true
  validates :title, presence: true, length: {maximum: 255}
  validates :address, presence: true
  validates :datetime, presence: true

  def pincode_valid?(pin2chek)
    pincode == pin2chek
  end

  def visitors
    (subscribers + [user]).uniq
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]
  before_action :set_event, except: [:index, :new, :create]
  before_action :password_guard!, only: [:show]
  after_action :verify_authorized, only: [:destroy, :update, :edit]


  def index
    @events = policy_scope(Event)
  end

  def show
    @new_comment = @event.comments.build(params[:comment])
    @new_photo = @event.photos.build(params[:photo])
    @new_subscription = @event.subscriptions.build(params[:subscription])
  end

  def new
    @event = current_user.events.build
    authorize @event
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)
    authorize @event

    if @event.save
      redirect_to @event, notice: I18n.t('controllers.events.created')
    else
      render :new
    end
  end

  def update
    if @event.update(event_params)
      redirect_to @event, notice: I18n.t('controllers.events.updated')
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_url, notice: I18n.t('controllers.events.destroyed')
  end

  private

  def password_guard!
    return true if @event.pincode.blank?
    return true if signed_in? && current_user == @event.user

    if params[:pincode].present? && @event.pincode_valid?(params[:pincode])
      cookies.permanent["events_#{@event.id}_pincode"] = params[:pincode]
    end

    pincode = cookies.permanent["events_#{@event.id}_pincode"]
    unless @event.pincode_valid?(pincode)
      if params[:pincode].present?
        flash.now[:alert] = I18n.t('controllers.events.wrong_pincode')
      end
      render 'password_form'
    end
  end


  def set_event
    @event = Event.find(params[:id])
    authorize @event
  end

  def event_params
    params.require(:event).permit(:title, :address, :datetime, :description, :pincode)
  end

end

app/helpers/events_helper.rb
module EventsHelper
  def cant_subscribe
    @event.user == current_user
  end
end

app/views/events/_event.html.slim
.col-sm-6.col-md-4.buffer-bottom
  .thumbnail
    = content_tag 'div', '', class: 'event-background',
            style: "background-image: url(#{event_photo(event)})"
    .thumbnail-inner.event-info-inner
      .caption
        .event-description
          h3
            = link_to event.title, event_path(event)
          h3
            small
              = l event.datetime, format: :short
          .buffer-both
            = event.address
        div
          - event.visitors.each do |user|
            = image_tag user_avatar_thumb(user), class: 'img-icon', title: user.name

app/views/events/_form.html.slim
= form_for(@event) do |f|
  = render partial: 'partials/form_errors', locals: {model: @event}
  .form-group
    = f.label :title
    = f.text_field :title, class: 'form-control'
  .form-group
    = f.label :address
    = f.text_field :address, class: 'form-control'
  .form-group
    = f.label :datetime
    p
      = f.text_field :datetime, class: 'form-control', data: { behavior: "flatpickr" },
              placeholder: t('activerecord.attributes.event.datetime')
  .form-group
    = f.label :description
    = f.text_area :description, class: 'form-control'
  .form-group
    = f.label :pincode
    = f.text_field :pincode, class: 'form-control'
  .actions
    = f.submit 'Сохранить', class: 'btn btn-primary'
    '
    = link_to 'вернуться', :back, class: 'btn btn-success'

app/views/events/edit.html.slim
h1 Редактировать событие
.row
  .col-md-6.buffer-top
    == render 'form'

app/views/events/index.html.slim
h1 События
.buffer-both
  - if policy(Event).create?
    = link_to 'Создать событие', new_event_path, class: 'btn btn-success'
.row.buffer-bottom
  = render partial: 'events/event', collection: @events

app/views/events/new.html.slim
h1 Новое событие
.row
  .col-md-6.buffer-top
    = render 'form'

app/views/events/password_form.html.slim
h1 Доступ только по пин-коду

= form_tag('', method: 'post') do |f|
  .form-group
    = label 'Пин-код', :pincode
    = password_field_tag :pincode, params[:pincode], class: 'form-control'

  .actions
    = submit_tag
= link_to 'На главную', events_path

app/views/events/show.html.slim
.row.justify-content-center
  .col-lg
    .event.container.shadow.shadow-lg.mt-5.center
      .event-info.row.m-0
        .col-md-12.mt-2.buffer-bottom
          = content_tag 'div', '', class: 'event-background',
                  style: "background-image: url(#{event_photo(@event)})"
          .event-info-inner.row
            .col-md-6.col-12
              .event-description
                h1 = @event.title
                h3 = l @event.datetime, format: :long
                h3.small = link_to @event.address, "https://yandex.ru/maps/?text=#{@event.address}", target: '_blank'
                / a [data-fancybox data-type="iframe" data-src="https://yandex.ru/maps/?text=#{@event.address}" href="javascript:;"]= @event.address
                p = @event.description
              - if current_user_can_edit?(@event)
                .row.justify-content-start
                  p &nbsp &nbsp
                  p = link_to 'Изменить', edit_event_path(@event), class: 'btn btn-success btn-block'
                  p &nbsp
                  p = link_to 'Удалить', event_path(@event), method: :delete,
                          data: {confirm: t('devise.registration.events.delete')}, class: 'btn btn-danger btn-block'
            .col-md-6.col-12.p-0
              div [id='map' data-address="#{@event.address}" style="width: 100%; height: 100%;"]
      .row
        .col-md-8
          .event-photo-gallery
            = render partial: 'photos/photo', collection: @event.photos.except(@new_photo)
          .event-photo-form.buffer-top.pl-3
            = render partial: 'photos/form', locals: {photo: @new_photo || @event.photos.build}
          .event-comments.buffer-top.pl-3
            = render partial: 'comments/form', locals: {comment: @new_comment || @event.comments.build}
          .buffer-both.pl-3
            = render partial: 'comments/comment', collection: @event.comments.except(@new_comment)
        .col-md-4
          .event-owner
            h4 Зовет:
            p = render partial: 'users/user', object: @event.user
          .event-subscriptions
            h4 Пойдут:
            p = render partial: 'subscriptions/subscription', collection: @event.subscriptions.except(@new_subscription)
          - if policy(@event).subscribe? && !@event.subscribers.include?(current_user)
            .event-subscription-form
              div = render partial: 'subscriptions/form', locals: {subscription: @new_subscription || @event.subscriptions.build}