config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "events#index"

  resources :events do
    resources :comments, only: [:create, :destroy]
    resources :subscriptions, only: [:create, :destroy]
    resources :photos, only: [:create, :destroy]

    post :show, on: :member
  end

  resources :users, only: [:show, :edit, :update]

end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :event
  belongs_to :user, optional: true

  validates :event, presence: true
  validates :user_name, presence: true, unless: -> { user.present? }
  validate :email_used?, on: :create, unless: -> { user.present? }
  validates :user_email, presence: true, 'valid_email_2/email': true, unless: -> { user.present? }

  validates :user, uniqueness: {scope: :event_id}, if: -> { user.present? }
  validates :user_email, uniqueness: {scope: :event_id}, unless: -> { user.present? }

  def user_name
    user.present? ? user.name : super
  end

  def user_email
    user.present? ? user.email : super
  end


  private

  def email_used?
    errors.add(:user_email, I18n.t('devise.messages.subscription.email_used')) if User.where(email: user_email).present?
  end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :set_event, only: [:create, :destroy]
  before_action :set_subscription, only: [:destroy]

  def create
    authorize @event, :subscribe?
    @new_subscription = @event.subscriptions.build(subscription_params)
    @new_subscription.user = current_user

    if @new_subscription.save
      EventMailer.subscription(@event, @new_subscription).deliver_later
      redirect_to @event, notice: t('controllers.subscriptions.created')
    else
      render 'events/show', alert: t('controllers.subscriptions.error')
    end
  end

  def destroy
    message = {notice: t('controllers.subscriptions.destroyed')}

    if current_user_can_edit?(@subscription)
      @subscription.destroy
    else
      message = {alert: t('controllers.subscriptions.error')}
    end

    redirect_to @event, message
  end

  private
  def set_subscription
    @subscription = @event.subscriptions.find(params[:id])
  end

  def set_event
    @event = Event.find(params[:event_id])
  end

  def subscription_params
    params.fetch(:subscription, {}).permit(:user_email, :user_name)
  end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/_form.html.slim
= form_for [@event, subscription] do |f|
  = render partial: 'partials/form_errors', locals: {model: subscription}

  - unless user_signed_in?
    .form-group
      = f.text_field :user_name, class: 'form-control', placeholder: t('activerecord.attributes.user.name')
    .form-group
      = f.email_field :user_email, class: 'form-control', placeholder: 'email'

  .actions
    = f.submit 'Подписаться', class: 'btn btn-primary'

app/views/subscriptions/_subscription.html.slim
span.subscription
  - if subscription.user.present?
    => render partial: 'users/user', object: subscription.user
  - else
    em => subscription.user_name
  - if current_user_can_edit?(subscription)
    => link_to event_subscription_path(subscription.event, subscription),
            method: :delete, data: {confirm: t('.destroy_confirm')} do
      span.fas.fa-times style="color: red"